apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-airflow-logs
spec:
  capacity:
    storage: {{ .Values.airflow.logs.persistence.size | quote }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.{{ .Release.Namespace }}.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-airflow-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.airflow.logs.persistence.size | quote }}
