apiVersion: v1
kind: Service
metadata:
  name: {{ template "airflow.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "airflow.name" . }}-web
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
#  nodeSelector:
#    airflow: true
  type: {{ .Values.airflow.service.type }}
  selector:
    app: {{ template "airflow.name" . }}-web
    release: {{ .Release.Name }}
  ports:
    - name: web
      protocol: TCP
      port: 8080
