kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ .Values.postgresql.persistence.storageClass }}"
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ .Values.airflow.logs.persistence.storageClass }}"
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  sharedv4: "true"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ .Values.airflow.dags.persistence.storageClass }}"
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  sharedv4: "true"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-airflow-misc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  sharedv4: "true"
allowVolumeExpansion: true
