kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.postgres.persistence.storageclass }}
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.airflow.logs.persistence.storageclass }}
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  sharedv4: "true"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.airflow.dags.persistence.storageclass }}
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  sharedv4: "true"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-airflow-misc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  sharedv4: "true"
allowVolumeExpansion: true
